/*
Built using Kango - Cross-browser extension framework.
http://kangoextensions.com/
*/
function KangoBrowserImpl(){this._eventTarget=new KangoEventTarget();var self=this;chrome.tabs.onActiveChanged.addListener(function(tabId,selectInfo){self._onTabChanged(tabId,selectInfo);});if(typeof chrome.webNavigation!='undefined'){chrome.webNavigation.onBeforeNavigate.addListener(function(details){self._onBeforeNavigate(details);});chrome.webNavigation.onDOMContentLoaded.addListener(function(details){self._onDOMContentLoaded(details);});}}
KangoBrowserImpl.prototype=kango.oop.extend(KangoBrowser,{_eventTarget:null,_onBeforeNavigate:function(details){if(details.frameId==0){var self=this;chrome.tabs.get(details.tabId,function(tab){var event={url:details.url,target:new KangoBrowserTabImpl(tab)};self._eventTarget.fireEvent(self.event.BeforeNavigate,event);});}},_onDOMContentLoaded:function(details){if(details.frameId==0){var self=this;chrome.tabs.get(details.tabId,function(tab){var event={url:details.url,title:tab.title,target:new KangoBrowserTabImpl(tab)};self._eventTarget.fireEvent(self.event.DocumentComplete,event);});}},_onTabChanged:function(tabId,selectInfo){var self=this;chrome.tabs.get(tabId,function(tab){var event={url:tab.url,title:tab.title,target:new KangoBrowserTabImpl(tab)};self._eventTarget.fireEvent(self.event.TabChanged,event);});},getName:function(){return'chrome';},windows:{getAll:function(callback){chrome.windows.getAll({populate:false},function(wins){var result=[];for(var i=0;i<wins.length;i++){result.push(new KangoBrowserWindowImpl(wins[i]))}
callback(result);});},getCurrent:function(callback){chrome.windows.getCurrent(function(win){callback(new KangoBrowserWindowImpl(win));});},create:function(details){chrome.windows.create({url:details.url,type:details.type,width:details.width,height:details.height});}},tabs:{getAll:function(callback){chrome.tabs.query({windowType:'normal'},function(tabs){var result=[];for(var i=0;i<tabs.length;i++){result.push(new KangoBrowserTabImpl(tabs[i]))}
callback(result);})},getCurrent:function(callback){chrome.windows.getCurrent(function(win){chrome.tabs.getSelected(win.windowId,function(tab){callback(new KangoBrowserTabImpl(tab));});});},create:function(details){var focused=(typeof details.focused!='undefined')?details.focused:true;chrome.tabs.create({url:details.url,active:focused});}}});function KangoBrowserWindowImpl(win){this._window=win;}
KangoBrowserWindowImpl.prototype=kango.oop.extend(KangoBrowserWindow,{_window:null,_getId:function(){return this._window.id;},getTabs:function(callback){chrome.tabs.getAllInWindow(this._window.windowId,function(tabs){var result=[];for(var i=0;i<tabs.length;i++){result.push(new KangoBrowserTabImpl(tabs[i]))}
callback(result);});},getCurrentTab:function(callback){chrome.tabs.getSelected(this._window.windowId,function(tab){callback(new KangoBrowserTabImpl(tab));});},isActive:function(){return this._window.focused;}});function KangoBrowserTabImpl(tab){this._tab=tab;}
KangoBrowserTabImpl.prototype=kango.oop.extend(KangoBrowserTab,{_tab:null,_getId:function(){return this._tab.id;},getUrl:function(){return this._tab.url;},getTitle:function(){return this._tab.title;},getDOMWindow:function(){return null;},isActive:function(){return this._tab.active;},navigate:function(url){chrome.tabs.update(this._getId(),{url:url});},dispatchMessage:function(name,data){var event={name:name,data:data,origin:'background',target:null,source:null};chrome.tabs.sendRequest(this._tab.id,event,function(){});}});kango.browser=new KangoBrowserImpl();