/*
Built using Kango - Cross-browser extension framework.
http://kangoextensions.com/
*/
function KangoBrowserImpl(){this._eventTarget=new KangoEventTarget();var self=this;opera.extension.tabs.addEventListener('focus',function(){self._onTabChanged();},false);opera.extension.tabs.addEventListener('close',function(){self._onTabChanged();},false);opera.extension.tabs.addEventListener('create',function(){self._onTabChanged();},false);kango.addEventListener(kango.event.Ready,function(){kango.addMessageListener('KangoBrowser_DOMContentLoaded',function(event){self._onDOMContentLoaded(event.target,event.data);});kango.addMessageListener('KangoBrowser_BeforeNavigate',function(event){self._onBeforeNavigate(event.target,event.data);});});}
KangoBrowserImpl.prototype=kango.oop.extend(KangoBrowser,{_eventTarget:null,_onBeforeNavigate:function(target,data){var event={url:data.url,target:target};this._eventTarget.fireEvent(this.event.BeforeNavigate,event);},_onDOMContentLoaded:function(target,data){var event={url:data.url,title:data.title,target:target};this._eventTarget.fireEvent(this.event.DocumentComplete,event);},_onTabChanged:function(e){var tab=opera.extension.tabs.getFocused();if(tab!=null){var event={url:tab.url,title:tab.title,target:new KangoBrowserTabImpl(tab)};this._eventTarget.fireEvent(this.event.TabChanged,event);}},getName:function(){return'opera';},windows:{getAll:function(callback){var wins=opera.extension.windows.getAll();var result=[];for(var i=0;i<wins.length;i++){result.push(new KangoBrowserWindowImpl(wins[i]))}
callback(result);},getCurrent:function(callback){var win=opera.extension.windows.getFocused();if(win!=null){callback(new KangoBrowserWindowImpl(win));}
else{var wins=opera.extension.windows.getAll();if(wins.length!=0){callback(new KangoBrowserWindowImpl(wins[0]));}}},create:function(details){opera.extension.windows.create().tabs[0].url=details.url;}},getTabFromUrl:function(url){var tab=opera.extension.tabs.getFocused();if(tab==null||tab.url!=url){var wins=opera.extension.windows.getAll();for(var i=0;i<wins.length;i++){var tabs=wins[i].tabs;for(var j=0;j<tabs.length;j++){if(tabs[j].url==url){tab=tabs[j];if(tabs[j].focused){break;}}}}}
return new KangoBrowserTabImpl(tab)}});KangoBrowserImpl.prototype.tabs.create=function(details){var focused=(typeof details.focused!='undefined')?details.focused:true;opera.extension.tabs.create({url:details.url,focused:focused});};function KangoBrowserWindowImpl(win){this._window=win;}
KangoBrowserWindowImpl.prototype=kango.oop.extend(KangoBrowserWindow,{_window:null,getTabs:function(callback){var result=[];var tabs=this._window.tabs;for(var i=0;i<tabs.length;i++){result.push(new KangoBrowserTabImpl(tabs[i]));}
callback(result);},getCurrentTab:function(callback){var tabs=this._window.tabs;var tab=null;for(var i=0;i<tabs.length;i++){if(tabs[i].focused){tab=new KangoBrowserTabImpl(tabs[i]);break;}}
callback(tab);},isActive:function(){return this._window.focused;}});function KangoBrowserTabImpl(tab){this._tab=tab;}
KangoBrowserTabImpl.prototype=kango.oop.extend(KangoBrowserTab,{_tab:null,getUrl:function(){return this._tab.url;},getTitle:function(){return'';},getDOMWindow:function(){return null;},isActive:function(){return this._tab.focused;},navigate:function(url){this.dispatchMessage('KangoBrowser_navigate',url);},dispatchMessage:function(name,data){this._tab.postMessage(JSON.stringify({name:name,data:data}));}});kango.browser=new KangoBrowserImpl();