/*
Built using Kango - Cross-browser extension framework.
http://kangoextensions.com/
*/
function KangoUIButton(element,details){this._element=element;this._eventListener=new KangoEventTarget();this._popup=new KangoUIPopup();this._popupDetails=null;this._icon='';this._badgeText='';this._badgeBackgroundColor=this._badgeDefaultBackgroundColor;this._image=null;var self=this;this._element.addEventListener('command',function(e){self._onCommand(e);},false);this._popup.addEventListener('PopupDocumentComplete',function(e){self._onPopupDocumentComplete(e);});this._initDetails(details);}
KangoUIButton.prototype={_element:null,_popup:null,_popupDetails:null,_eventListener:null,_icon:null,_badgeBackgroundColor:null,_badgeDefaultBackgroundColor:[45,2,180,255],_badgeText:'',_image:null,_initDetails:function(details){if(kango.lang.isObject(details)){if(kango.lang.isString(details.icon)){this.setIcon(details.icon);}
if(kango.lang.isString(details.caption)){this.setCaption(details.caption);}
if(kango.lang.isString(details.tooltipText)){this.setTooltipText(details.tooltipText);}
if(kango.lang.isObject(details.popup)){this._popupDetails=details.popup;}}},_onCommand:function(event){if(event.target.id==this._element.id){if(this._popupDetails!=null){var rect=this._element.getBoundingClientRect();var x=parseInt(this._element.boxObject.screenX+rect.width/2,10);var y=parseInt(this._element.boxObject.screenY+rect.height,10);this._popup.open({url:this._popupDetails.url,width:parseInt(this._popupDetails.width,10),height:parseInt(this._popupDetails.height,10),x:x,y:y});}
else{this._eventListener.fireEvent(this.event.Command);}}},_onPopupDocumentComplete:function(e){this._eventListener.fireEvent(this.event.PopupDocumentComplete,e);},_update:function(){function roundedRect(ctx,x,y,width,height,radius,fillColor){ctx.beginPath();ctx.moveTo(x,y+radius);ctx.lineTo(x,y+height-radius);ctx.quadraticCurveTo(x,y+height,x+radius,y+height);ctx.lineTo(x+width-radius,y+height);ctx.quadraticCurveTo(x+width,y+height,x+width,y+height-radius);ctx.lineTo(x+width,y+radius);ctx.quadraticCurveTo(x+width,y,x+width-radius,y);ctx.lineTo(x+radius,y);ctx.quadraticCurveTo(x,y,x,y+radius);ctx.fillStyle=fillColor;ctx.fill();}
var elem=this._element;if(this._image!=null){this._image.onload=function(){};delete this._image;this._image=null;}
var img=this._image=new Image();var self=this;var onloadHandler=function(){var marginLeft=-4;var imageWidth=img.width;var imageHeight=img.height;if(imageWidth>19||imageHeight>19){imageWidth=imageHeight=19;}
var canvas=document.getElementById('kango-ui-canvas');var context=canvas.getContext('2d');if(self._badgeText!=''){var textHeight=11;var font='bold '+textHeight+'px Tahoma,arial,helvetica,sans-serif';context.font=font;canvas.width=19;canvas.height=19;var textWidth=Math.round(context.measureText(self._badgeText).width);canvas.width=imageWidth+textWidth+2;canvas.height=imageHeight;context.drawImage(img,0,0,imageWidth,imageHeight);var backgroundColor='rgba('+self._badgeBackgroundColor[0]+', '+self._badgeBackgroundColor[1]+', '+self._badgeBackgroundColor[2]+', '+self._badgeBackgroundColor[3]/255+')';roundedRect(context,imageWidth+marginLeft,imageHeight-textHeight-1,textWidth+6,textHeight+1,4,backgroundColor);context.font=font;context.textBaseline='top';context.fillStyle='white';context.fillText(self._badgeText,imageWidth+marginLeft+2,imageHeight-textHeight);}
else{canvas.width=imageWidth;canvas.height=imageHeight;context.drawImage(img,0,0,imageWidth,imageHeight);}
elem.image=canvas.toDataURL('image/png');};var onloadCrutchHandler=function(){if(self._image!=null){if(self._image.complete){onloadHandler();}
else{window.setTimeout(onloadCrutchHandler,10);}}};img.onload=onloadCrutchHandler;img.src=this._icon;},event:{Command:'command',PopupDocumentComplete:'PopupDocumentComplete'},setTooltipText:function(text){this._element.setAttribute('tooltiptext',text);},setCaption:function(text){this._element.label=text;},setIcon:function(url){var path=url;if(url.indexOf(kango.SCHEME)==0||url.indexOf('http://')!=0||url.indexOf('https://')!=0){if(url!=''){path=kango.io.getExtensionFileUrl(url.replace(kango.SCHEME,''));}
else{this._element.removeAttribute('image');path='';}}
if(this._icon!=path){this._icon=path;this._update();}},setBadgeValue:function(val){val=(val!=null&&val!=0)?val.toString():'';if(this._badgeText!=val){this._badgeText=val;this._update();}},setBadgeBackgroundColor:function(color){if(color!=null&&kango.lang.isArray(color)&&color.length>=4){this._badgeBackgroundColor=color;this._update();}},setPopup:function(details){this._popupDetails=details;},closePopup:function(){this._popup.close();},addEventListener:function(name,callback){return this._eventListener.addEventListener(name,callback);},removeEventListener:function(name,callback){return this._eventListener.removeEventListener(name,callback);},setContextMenu:function(itemName,callback){var button=this._element;var menupopup=document.createElement('menupopup');var popupId=button.id+'-menu';menupopup.setAttribute('id',popupId);button.appendChild(menupopup);var itemElem=document.createElement('menuitem');itemElem.setAttribute('label',itemName);itemElem.addEventListener('command',function(e){callback();e.preventDefault();},false);menupopup.appendChild(itemElem);this._element.addEventListener('contextmenu',function(e){menupopup.openPopup(button,'after_start',0,0,true,false);e.preventDefault();},false);}};kango.ui={_eventListener:new KangoEventTarget(),_init:function(){var toolbar=kango.getExtensionInfo().toolbar;if(kango.lang.isObject(toolbar)){kango.ui.toolbar=new KangoUIToolbar();}
var browser_button=kango.getExtensionInfo().browser_button;if(kango.lang.isObject(browser_button)){kango.ui.browserButton=new KangoUIBrowserButton(browser_button);}
return this._eventListener.dispatchEvent(new KangoEvent(this.event.Ready));},event:{Ready:'Ready'},addEventListener:function(name,callback){return this._eventListener.addEventListener(name,callback);},removeEventListener:function(name,callback){return this._eventListener.removeEventListener(name,callback);},popup:{close:function(win){kango.ui.browserButton.closePopup();}}};kango.addEventListener(kango.event.Ready,function(){kango.ui._init();});