/*
 * File: app/model/WorkHourModel.js
 *
 * This file was generated by Sencha Designer version 2.0.0.
 * http://www.sencha.com/products/designer/
 *
 * This file requires use of the Ext JS 4.0.x library, under independent license.
 * License of Sencha Designer does not include license for Ext JS 4.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('TsmcBuddy.model.WorkHourModel', {
    extend: 'Ext.data.Model',

    fields: [
        {
            dateFormat: 'Y/m/d',
            name: 'date'
        },
        {
            convert: function(v, rec) {
                var time = v.split(':');
                if(time[0]<8){
                    return new Date(1970,0,2,time[0],time[1],0);
                }else{
                    return new Date(1970,0,1,time[0],time[1],0);
                }
            },
            dateFormat: 'H:i',
            name: 'time',
            type: 'date'
        }
    ]
});