/*
Built using Kango - Cross-browser extension framework.
http://kangoextensions.com/
*/
function KangoWebProgressListener(callback){this._callback=callback;}
KangoWebProgressListener.prototype={_callback:null,QueryInterface:function(aIID){if(aIID.equals(Components.interfaces.nsIWebProgressListener)||aIID.equals(Components.interfaces.nsISupportsWeakReference)||aIID.equals(Components.interfaces.nsISupports))
return this;throw Components.results.NS_NOINTERFACE;},onProgressChange:function(aWebProgress,aRequest,aCurSelfProgress,aMaxSelfProgress,aCurTotalProgress,aMaxTotalProgress){},onStatusChange:function(aWebProgress,aRequest,aStatus,aMessage){},onSecurityChange:function(aWebProgress,aRequest,aState){},onLocationChange:function(aProgress,aRequest,aLocation){},onStateChange:function(aWebProgress,aRequest,aStateFlags,aStatus){var nsIWebProgressListener=Components.interfaces.nsIWebProgressListener;if(aStateFlags&nsIWebProgressListener.STATE_START&&aStateFlags&nsIWebProgressListener.STATE_IS_DOCUMENT){var nsIChannel=Components.interfaces.nsIChannel;var event={url:aRequest.QueryInterface(nsIChannel).originalURI.spec,window:aWebProgress.DOMWindow,document:aWebProgress.DOMWindow.document};this._callback(event);}}};function KangoBrowserImpl(){var self=this;this._eventTarget=new KangoEventTarget();this._webProgressListener=new KangoWebProgressListener(function(event){self._onPageBeforeNavigate(event)});kango.addEventListener(kango.event.Ready,function(){self._subscribeEvents();});}
KangoBrowserImpl.prototype=kango.oop.extend(KangoBrowser,{_eventTarget:null,_webProgressListener:null,_subscribeEvents:function(){var self=this;document.getElementById('appcontent').addEventListener('DOMContentLoaded',function(event){self._onPageLoad(event);},true);gBrowser.addProgressListener(this._webProgressListener,Components.interfaces.nsIWebProgress.NOTIFY_STATE_DOCUMENT);gBrowser.tabContainer.addEventListener('TabSelect',function(event){self._onTabChanged(null);},false);},_onPageBeforeNavigate:function(event){if(!event.document.defaultView.frameElement){var win=event.document.defaultView.top;var doc=win.document;var e={url:event.url,target:new KangoBrowserTabImpl(win)};this._eventTarget.fireEvent(this.event.BeforeNavigate,e);}},_onPageLoad:function(event){var doc=event.originalTarget;if(doc instanceof HTMLDocument){var win=doc.defaultView;var url='';try{url=doc.location.href;}
catch(ex){}
var e={url:url,title:doc.title||'',target:new KangoBrowserTabImpl(win)};if(!doc.defaultView.frameElement){this._eventTarget.fireEvent(this.event.DocumentComplete,e);}
e.window=win;this._eventTarget.fireEvent('DOMContentLoaded',e);}},_onTabChanged:function(event){var doc=window.content.document;var win=doc.defaultView;var url='';try{url=doc.location.href;}
catch(ex){}
var e={url:url,title:doc.title||'',target:new KangoBrowserTabImpl(win)};this._eventTarget.fireEvent(this.event.TabChanged,e);},getName:function(){return'firefox';},windows:{getAll:function(callback){var wm=Components.classes['@mozilla.org/appshell/window-mediator;1'].getService(Components.interfaces.nsIWindowMediator);var browserEnumerator=wm.getEnumerator('navigator:browser');var result=[];while(browserEnumerator.hasMoreElements()){result.push(new KangoBrowserWindowImpl(browserEnumerator.getNext().gBrowser));}
callback(result);},getCurrent:function(callback){callback(new KangoBrowserWindowImpl(gBrowser));},create:function(details){throw new KangoNotImplementedException();}},getTabProxyForWindow:function(win){var proxyName='KangoTabProxy_'+kango.getExtensionInfo().id;if(typeof win[proxyName]=='undefined'){win[proxyName]=new KangoTabProxy(new KangoBrowserTabImpl(win));}
return win[proxyName];}});KangoBrowserImpl.prototype.tabs.create=function(details){var tab=gBrowser.addTab(details.url);if(typeof details.focused=='undefined'||details.focused){gBrowser.selectedTab=tab;}};function KangoBrowserWindowImpl(tabbrowser){this._tabbrowser=tabbrowser;}
KangoBrowserWindowImpl.prototype=kango.oop.extend(KangoBrowserWindow,{_tabbrowser:null,getTabs:function(callback){var result=[];var tabContainer=this._tabbrowser.tabContainer;for(var i=0;i<tabContainer.childNodes.length;i++){result.push(new KangoBrowserTabImpl(gBrowser.getBrowserForTab(this._tab).contentWindow));}
callback(result);},getCurrentTab:function(callback){callback(new KangoBrowserTabImpl(gBrowser.getBrowserForTab(this._tab).contentWindow));},isActive:function(){return true;}});function KangoBrowserTabImpl(win){this._win=win;this._tab=this._getTabFromWindow(win);}
KangoBrowserTabImpl.prototype=kango.oop.extend(KangoBrowserTab,{_tab:null,_win:null,_getTabFromWindow:function(win){var targetBrowserIndex=gBrowser.getBrowserIndexForDocument(win.top.document);if(targetBrowserIndex!=-1){return gBrowser.tabContainer.childNodes[targetBrowserIndex];}
return null},getUrl:function(){var url='';try{url=this.getDOMWindow().document.location.href;}
catch(e){}
return url;},getTitle:function(){var title='';try{title=this.getDOMWindow().document.title;}
catch(e){}
return title;},getDOMWindow:function(){return this._win.wrappedJSObject;},isActive:function(){return this._tab.selected;},navigate:function(url){gBrowser.getBrowserForTab(this._tab).setAttribute('src',url);},dispatchMessage:function(name,data){var event={name:name,data:data,origin:'tab',source:kango,target:kango};kango.browser.getTabProxyForWindow(this._win).fireEvent('message',event);}});kango.browser=new KangoBrowserImpl();