/*
Built using Kango - Cross-browser extension framework.
http://kangoextensions.com/
*/
function KangoPersistProgressListener(aPersist,localFile){this.localFile=localFile;this.persist=aPersist;this.onFinish=function(status){};}
KangoPersistProgressListener.prototype.QueryInterface=function(aIID){if(aIID.equals(Components.interfaces.nsIWebProgressListener)){return this;}
throw Components.results.NS_NOINTERFACE;};KangoPersistProgressListener.prototype.onProgressChange=KangoPersistProgressListener.prototype.onLocationChange=KangoPersistProgressListener.prototype.onStatusChange=KangoPersistProgressListener.prototype.onSecurityChange=function(){};KangoPersistProgressListener.prototype.onStateChange=function(aWebProgress,aRequest,aStateFlags,aStatus){if(this.persist.currentState==this.persist.PERSIST_STATE_FINISHED){var status=200;try{if(aRequest!=null){var channel=aRequest.QueryInterface(Components.interfaces.nsIHttpChannel);status=channel.responseStatus;}}
catch(e){}
this.onFinish(status);}};var KangoVersionComparator={_addZeros:function(arr,len){for(var i=0;i<len;i++){arr.push(0);}
return arr;},isNewer:function(strNewVersion,strOldVersion){var newa=strNewVersion.split('.');var olda=strOldVersion.split('.');var iNewLen=newa.length;var iOldLen=olda.length;if(iNewLen>iOldLen){olda=this._addZeros(olda,iNewLen-iOldLen);}
else if(iOldLen>iNewLen){newa=this._addZeros(newa,iOldLen-iNewLen);}
for(var i=0;i<newa.length;i++){if(parseInt(newa[i])>parseInt(olda[i])){return true;}
else if(parseInt(newa[i])<parseInt(olda[i])){return false;}}
return false;}};var KangoUpdater={_updateInterval:(1000*60*60*24),_timer:null,_updateUrl:'',init:function(){this._updateUrl=kango.getExtensionInfo().update_url;if(typeof this._updateUrl!='undefined'&&this._updateUrl!=''){this.checkForNewVersion(this._updateUrl);this._timer=setInterval(function(){self.checkForNewVersion(self._updateUrl);},this._updateInterval/2);}},checkForNewVersion:function(aUrl){var self=this;KangoCachedHttpRequest.send(this._updateUrl,'GET',null,this._updateInterval,function(text){var parser=new DOMParser();var xmlDoc=parser.parseFromString(text,'text/xml');var version=xmlDoc.getElementsByTagName('version')[0].firstChild.nodeValue;var url=xmlDoc.getElementsByTagName('url')[0].firstChild.nodeValue;if(KangoVersionComparator.isNewer(version,kango.getExtensionInfo().version)){KangoUpdater.update(url);}});},createDirectory:function(extractedFile){if(!extractedFile.exists()||!extractedFile.isDirectory()){extractedFile.create(Components.interfaces.nsIFile.DIRECTORY_TYPE,0777);}},extractZipFile:function(aFile,aPath){var zReader=Components.classes["@mozilla.org/libjar/zip-reader;1"].createInstance(Components.interfaces.nsIZipReader);zReader.open(aFile);var collection=zReader.findEntries('*');while(collection.hasMore()){var obj=collection.getNext();var extractedFile=Components.classes["@mozilla.org/file/local;1"].createInstance(Components.interfaces.nsILocalFile);var extractedPath=aPath.path;var delimiter1=((extractedPath.search(/\\/)!=-1)?"\\":"/");var delimiter2=((obj.search(/\\/)!=-1)?"\\":"/");var newpath=obj.split(delimiter2).join(delimiter1);var mass=obj.split(delimiter2);var name=mass[mass.length-1];extractedPath+=delimiter1+newpath;extractedFile.initWithPath(extractedPath);if(name==''){this.createDirectory(extractedFile);}
else{var path=extractedPath.substr(0,extractedPath.lastIndexOf(delimiter1));var extractedDir=Components.classes["@mozilla.org/file/local;1"].createInstance(Components.interfaces.nsILocalFile);extractedDir.initWithPath(path);this.createDirectory(extractedDir);zReader.extract(obj,extractedFile);}}
zReader.close();},update:function(aUrl){try{var persist=Components.classes["@mozilla.org/embedding/browser/nsWebBrowserPersist;1"].createInstance(Components.interfaces.nsIWebBrowserPersist);var localFile=Components.classes["@mozilla.org/file/directory_service;1"].getService(Components.interfaces.nsIProperties).get("ProfD",Components.interfaces.nsIFile);localFile.append('extensions');localFile.append('update.zip');var obj_URI=Components.classes["@mozilla.org/network/io-service;1"].getService(Components.interfaces.nsIIOService).newURI(aUrl,null,null);var progressListener=new KangoPersistProgressListener(persist,localFile);progressListener.onFinish=function(status){if(status==200){try{var targetDirectory=Components.classes["@mozilla.org/file/directory_service;1"].getService(Components.interfaces.nsIProperties).get("ProfD",Components.interfaces.nsIFile);targetDirectory.append('extensions');targetDirectory.append(kango.getExtensionInfo().id);KangoUpdater.extractZipFile(localFile,targetDirectory);localFile.remove(false);}catch(e){}}};var nsIWBP=Components.interfaces.nsIWebBrowserPersist;persist.persistFlags=nsIWBP.PERSIST_FLAGS_REPLACE_EXISTING_FILES|nsIWBP.PERSIST_FLAGS_BYPASS_CACHE;persist.progressListener=progressListener;persist.saveURI(obj_URI,null,null,null,"",localFile);}catch(e){}}};kango.addEventListener(kango.event.Ready,function(){KangoUpdater.init();});