/*
 * File: app/view/TopViewport.js
 *
 * This file was generated by Sencha Designer version 2.0.0.
 * http://www.sencha.com/products/designer/
 *
 * This file requires use of the Ext JS 4.0.x library, under independent license.
 * License of Sencha Designer does not include license for Ext JS 4.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('TsmcBuddy.view.TopViewport', {
    extend: 'Ext.container.Viewport',

    layout: {
        type: 'fit'
    },

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'tabpanel',
                    id: 'mainTabPanel',
                    activeTab: 3,
                    items: [
                        {
                            xtype: 'panel',
                            html: '<iframe style="position:absolute;top:0px;left:0px;" width="100%" height="100%" src="http://f8cmydev1.tsmc.com.tw:7091/conf/main.do?operation=showComm" scrolling="no" frameborder="0"></iframe>',
                            id: 'pfPanel',
                            title: 'My',
                            items: [
                                {
                                    xtype: 'button',
                                    hidden: true,
                                    id: 'conf20Btn',
                                    margin: 20,
                                    style: 'position:absolute;z-index:1000000;',
                                    text: 'Click here for NTLM login first',
                                    listeners: {
                                        click: {
                                            fn: me.onConf20BtnClick,
                                            scope: me
                                        }
                                    }
                                }
                            ],
                            listeners: {
                                afterrender: {
                                    fn: me.onPfPanelAfterRender,
                                    scope: me
                                }
                            }
                        },
                        {
                            xtype: 'form',
                            id: 'callPanel',
                            layout: {
                                type: 'absolute'
                            },
                            title: 'Call',
                            items: [
                                {
                                    xtype: 'textfield',
                                    id: 'callFromField',
                                    style: 'line-height:48px;',
                                    width: 260,
                                    fieldStyle: 'font-size:48px; height:60px;',
                                    fieldLabel: '',
                                    labelWidth: 50,
                                    allowBlank: false,
                                    emptyText: 'From',
                                    maxLength: 7,
                                    minLength: 7,
                                    regex: /7\d{6}/,
                                    regexText: 'Illegal phone number',
                                    x: 10,
                                    y: 10
                                },
                                {
                                    xtype: 'textfield',
                                    id: 'callToField',
                                    style: 'line-height:48px;',
                                    width: 260,
                                    fieldStyle: 'font-size:48px; height:60px;',
                                    fieldLabel: '',
                                    labelWidth: 50,
                                    allowBlank: false,
                                    emptyText: 'To',
                                    maxLength: 7,
                                    minLength: 7,
                                    regex: /7\d{6}/,
                                    regexText: 'Illegal phone number',
                                    x: 10,
                                    y: 80
                                },
                                {
                                    xtype: 'button',
                                    height: 30,
                                    id: 'callBtn',
                                    width: 260,
                                    text: 'GO',
                                    x: 10,
                                    y: 150
                                }
                            ]
                        },
                        {
                            xtype: 'panel',
                            id: 'smsPanel',
                            layout: {
                                type: 'absolute'
                            },
                            title: 'Text',
                            items: [
                                {
                                    xtype: 'textfield',
                                    id: 'smsBylineField',
                                    width: 260,
                                    fieldLabel: '',
                                    labelWidth: 50,
                                    emptyText: '署名',
                                    x: 10,
                                    y: 10
                                },
                                {
                                    xtype: 'textfield',
                                    id: 'smsDestField',
                                    width: 260,
                                    fieldLabel: '',
                                    labelWidth: 50,
                                    emptyText: '對方MVPN',
                                    x: 10,
                                    y: 40
                                },
                                {
                                    xtype: 'textareafield',
                                    height: 140,
                                    id: 'smsTextField',
                                    width: 260,
                                    fieldLabel: '',
                                    emptyText: '簡訊內容',
                                    x: 10,
                                    y: 70
                                },
                                {
                                    xtype: 'button',
                                    height: 30,
                                    width: 260,
                                    text: 'GO',
                                    x: 10,
                                    y: 220,
                                    listeners: {
                                        click: {
                                            fn: me.onSmsButtonClick,
                                            scope: me
                                        }
                                    }
                                }
                            ]
                        },
                        {
                            xtype: 'form',
                            id: 'pwPanel',
                            layout: {
                                type: 'absolute'
                            },
                            title: 'Password',
                            items: [
                                {
                                    xtype: 'textfield',
                                    id: 'pwNtField',
                                    width: 250,
                                    name: 'RequestUser',
                                    allowBlank: false,
                                    emptyText: '帳號(NT)',
                                    vtype: 'alpha',
                                    x: 10,
                                    y: 40
                                },
                                {
                                    xtype: 'textfield',
                                    id: 'pwIdField',
                                    width: 250,
                                    name: 'UserID',
                                    allowBlank: false,
                                    emptyText: '身分證字號',
                                    vtype: 'alphanum',
                                    x: 10,
                                    y: 70
                                },
                                {
                                    xtype: 'textfield',
                                    id: 'pwTelField',
                                    width: 250,
                                    name: 'TEL',
                                    allowBlank: false,
                                    emptyText: '家中電話末六碼',
                                    enforceMaxLength: true,
                                    maxLength: 6,
                                    minLength: 6,
                                    x: 10,
                                    y: 130
                                },
                                {
                                    xtype: 'textfield',
                                    id: 'pwEmergencyField',
                                    width: 250,
                                    name: 'Emergency',
                                    emptyText: '緊急聯絡人',
                                    x: 10,
                                    y: 160
                                },
                                {
                                    xtype: 'textfield',
                                    id: 'pwField',
                                    width: 250,
                                    name: 'Password1',
                                    allowBlank: false,
                                    emptyText: '新密碼',
                                    x: 10,
                                    y: 190
                                },
                                {
                                    xtype: 'datefield',
                                    id: 'pwDateField',
                                    width: 250,
                                    allowBlank: false,
                                    emptyText: '出生年月日',
                                    format: 'Y/m/d',
                                    showToday: false,
                                    x: 10,
                                    y: 100,
                                    listeners: {
                                        expand: {
                                            fn: me.onDatefieldExpand,
                                            scope: me
                                        }
                                    }
                                },
                                {
                                    xtype: 'radiogroup',
                                    id: 'pwTypeRadio',
                                    width: 310,
                                    fieldLabel: '',
                                    allowBlank: false,
                                    x: 10,
                                    y: 10,
                                    items: [
                                        {
                                            xtype: 'radiofield',
                                            name: 'type',
                                            boxLabel: '重設Notes密碼(50循環)',
                                            inputValue: 'notes'
                                        },
                                        {
                                            xtype: 'radiofield',
                                            name: 'type',
                                            boxLabel: '重設NT密碼',
                                            checked: true,
                                            inputValue: 'nt'
                                        }
                                    ]
                                },
                                {
                                    xtype: 'button',
                                    height: 30,
                                    width: 250,
                                    text: 'GO',
                                    x: 10,
                                    y: 220,
                                    listeners: {
                                        click: {
                                            fn: me.onPwButtonClick,
                                            scope: me
                                        }
                                    }
                                }
                            ]
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    },

    onConf20BtnClick: function(button, e, options) {
        window.open('http://f8cmydev1.tsmc.com.tw:7091/conf/main.do?operation=showComm&dispType=conference','_blank');

    },

    onPfPanelAfterRender: function(abstractcomponent, options) {
        var me = this;
        Ext.Ajax.request({
            method: 'GET',
            url: 'http://f8cmydev1.tsmc.com.tw:7091/conf/main.do?operation=showComm&dispType=conference',
            success: function(response){
            },
            failure: function(response){
                Ext.getCmp('conf20Btn').show();
            }
        });

    },

    onSmsButtonClick: function(button, e, options) {
        Ext.Ajax.request({
            method: 'POST',
            url: 'http://f8cmydev1.tsmc.com.tw:7091/conf/phone.do',
            params:{
                operation: 'sendSms',
                sender: Ext.getCmp('smsBylineField').getValue(),
                sendSmsObjArry:Ext.encode([{
                    "id":"",
                    "ntAccount":"",
                    "phone": Ext.getCmp('smsDestField').getValue(),
                    "name":"test",
                "isMvpn":1}]),
                text: Ext.getCmp('smsTextField').getValue()
            },
            success: function(response){
                var result = Ext.decode(response.responseText);        
                var info = Ext.Msg.show({
                    title:'傳送成功',
                    msg: result.message + '<br/>' + '本訊息將於1秒後自動關閉'
                });   
                Ext.Function.defer(function(){
                    info.hide();
                },2000);
            },
            failure: function(response){
                var result = Ext.decode(response.responseText);
                Ext.Msg.alert('傳送失敗',result.msg);
            }
        });
    },

    onDatefieldExpand: function(field, options) {
        field.getPicker().setValue(new Date(1980,0,1));
        field.getPicker().showMonthPicker();
    },

    onPwButtonClick: function(button, e, options) {
        /*
        var vals = Ext.getCmp('pwPanel').getForm().getFieldValues();
        document.pwNotesForm.RequestUser.value = vals.RequestUser;
        document.pwNotesForm.UserID.value = vals.UserID;
        document.pwNotesForm.BirthYear.value = Ext.getCmp('pwDateField').getValue().getFullYear();
        document.pwNotesForm.BirthMonth.value = Ext.getCmp('pwDateField').getValue().getMonth() +1;
        document.pwNotesForm.BirthDay.value = Ext.getCmp('pwDateField').getValue().getDate();
        document.pwNotesForm.TEL.value = vals.TEL;
        document.pwNotesForm.Emergency.value = vals.Emergency;
        document.pwNotesForm.Password1.value = vals.Password1;
        document.pwNotesForm.Password2.value = vals.Password1;
        document.pwNotesForm.submit();

        Ext.Ajax.defaultPostHeader = "application/x-www-form-urlencoded; charset=big5";
        Ext.getCmp('pwPanel').getForm().submit({
        url: 'http://pcmsweb:2345/default.asp',
        method: 'POST'
        });
        */

        if(!Ext.getCmp('pwPanel').getForm().isValid()){
            return;
        }

        var birthYear = Ext.getCmp('pwDateField').getValue().getFullYear();
        var birthMonth = Ext.getCmp('pwDateField').getValue().getMonth() +1;
        var birthDay = Ext.getCmp('pwDateField').getValue().getDate();


        if(Ext.getCmp('pwTypeRadio').getValue().type == 'nt'){
            Ext.Ajax.request({
                url: 'http://pcmsweb/resetpassword/default.asp',
                method: 'POST',
                params: {
                    RequestUser: Ext.getCmp('pwNtField').getValue(),
                    UserID: Ext.getCmp('pwIdField').getValue(),
                    BirthYear: birthYear,
                    BirthMonth: birthMonth,
                    BirthDay: birthDay,
                    TEL: Ext.getCmp('pwTelField').getValue(),
                    Password1: Ext.getCmp('pwField').getValue(),
                    Password2: Ext.getCmp('pwField').getValue(),
                    Action:'submit'
                },
                success: function(response){

                }
            });

        }else{
            console.log('notes');
            var tempComp = Ext.create('Ext.Component', {
                html: '<iframe name="'+Ext.id()+'" src="resetNotesPw.html"></iframe>',
                hidden: true,
                renderTo: Ext.getBody()
            });
        }
    }

});