/*
 * File: app/controller/MainController.js
 *
 * This file was generated by Sencha Designer version 2.0.0.
 * http://www.sencha.com/products/designer/
 *
 * This file requires use of the Ext JS 4.0.x library, under independent license.
 * License of Sencha Designer does not include license for Ext JS 4.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('TsmcBuddy.controller.MainController', {
    extend: 'Ext.app.Controller',
    alias: 'controller.main',

    models: [
        'WorkHourModel'
    ],
    stores: [
        'WorkHourStore'
    ],
    views: [
        'TopViewport'
    ],
    init: function() {
        this.control({
            "#callPanel > field": {
                specialkey: this.onCallfieldEnter
            },
            "#callPanel > button": {
                click: this.onButtonClick
            }
        });
    },

    onCallfieldEnter: function(field, e, options) {
        if(e.keyCode == e.ENTER) {
            field.focus(true);
            //this.onCallButtonClick();
            this.callTsmcPhone();
        }
    },

    onButtonClick: function(button, e, options) {

        this.callTsmcPhone();
    },

    callTsmcPhone: function() {
        if(Ext.getCmp('callPanel').getForm().isValid()){

            var from = Ext.getCmp('callFromField').getValue();
            var to = Ext.getCmp('callFromField').getValue();
            var wait = Ext.Msg.wait('打給'+to +'中...<br/>請拿起您的話筒');

            Ext.Ajax.request({
                method:'GET',
                url: 'http://f8cmydev1.tsmc.com.tw:7091/conf/phone.do',
                params:{
                    operation: 'createWebCallMeeting',
                    gcInputObj: Ext.encode({
                        sourcePhone: from,
                        targetPhone: to
                    })
                },
                success: function(response){
                    var result = Ext.decode(response.responseText);
                    var msg = '';
                    if(!Ext.isEmpty(result.resultdesc)){
                        msg = result.resultdesc;
                    }else{
                        msg = result.msg;
                    }
                    wait.hide();
                    var info = Ext.Msg.show({
                        title:'Call Result',
                        msg:msg + '<br/>' + '本訊息將於1秒後自動關閉'
                    });   
                    Ext.Function.defer(function(){
                        info.hide();
                    },2000);
                },
                failure: function(response){
                    var result = Ext.decode(response.responseText);
                    wait.hide();
                    Ext.Msg.alert('呼叫失敗',result.msg);
                }
            });

        }
    }

});