/*
Built using Kango - Cross-browser extension framework.
http://kangoextensions.com/
*/
function KangoBrowserImpl(){this._eventTarget=new KangoEventTarget();var self=this;safari.application.addEventListener('beforeNavigate',function(e){self._onBeforeNavigate(e)},true);safari.application.addEventListener('navigate',function(e){self._onNavigate(e)},true);safari.application.addEventListener('activate',function(e){self._onActivate(e)},true);}
KangoBrowserImpl.prototype=kango.oop.extend(KangoBrowser,{_eventTarget:null,_onBeforeNavigate:function(event){var e={url:event.url,target:new KangoBrowserTabImpl(event.target)};this._eventTarget.fireEvent(this.event.BeforeNavigate,e);},_onNavigate:function(event){var tab=event.target;var e={url:tab.url||'',title:tab.title||'',target:new KangoBrowserTabImpl(tab)};this._eventTarget.fireEvent(this.event.DocumentComplete,e);},_onActivate:function(event){if(event.target instanceof SafariBrowserTab){var tab=event.target;var e={url:tab.url||'',title:tab.title||'',target:new KangoBrowserTabImpl(tab)};this._eventTarget.fireEvent(this.event.TabChanged,e);}},getName:function(){return'safari';},windows:{getAll:function(callback){var wins=safari.application.browserWindows;var result=[];for(var i=0;i<wins.length;i++){result.push(new KangoBrowserWindowImpl(wins[i]))}
callback(result);},getCurrent:function(callback){callback(new KangoBrowserWindowImpl(safari.application.activeBrowserWindow));},create:function(details){safari.application.openBrowserWindow().activeTab.url=details.url;}},tabs:{getAll:function(callback){var result=[];var wins=safari.application.browserWindows;for(var i=0;i<wins.length;i++){var tabs=wins[i].tabs;for(var j=0;j<tabs.length;j++){result.push(new KangoBrowserTabImpl(tabs[j]));}}
callback(result);},getCurrent:function(callback){callback(new KangoBrowserTabImpl(safari.application.activeBrowserWindow.activeTab));},create:function(details){var focused=(typeof details.focused!='undefined')?details.focused:true;safari.application.activeBrowserWindow.openTab(focused?'foreground':'background').url=details.url;}}});function KangoBrowserWindowImpl(win){this._window=win;}
KangoBrowserWindowImpl.prototype=kango.oop.extend(KangoBrowserWindow,{_window:null,getTabs:function(callback){var result=[];var tabs=this._window.tabs;for(var i=0;i<tabs.length;i++){result.push(new KangoBrowserTabImpl(tabs[i]));}
callback(result);},getCurrentTab:function(callback){callback(new KangoBrowserTabImpl(this._window.activeTab));},isActive:function(){return(safari.application.activeBrowserWindow==this._window);}});function KangoBrowserTabImpl(tab){this._tab=tab;}
KangoBrowserTabImpl.prototype=kango.oop.extend(KangoBrowserTab,{_tab:null,getUrl:function(){return this._tab.url||'';},getTitle:function(){return this._tab.title||'';},getDOMWindow:function(){return null;},isActive:function(){return(this._tab==this._tab.browserWindow.activeTab);},navigate:function(url){this._tab.url=url;},dispatchMessage:function(name,data){if(typeof this._tab.page!='undefined'){this._tab.page.dispatchMessage(name,data);}}});kango.browser=new KangoBrowserImpl();