/*
 * File: app/view/TopViewport.js
 *
 * This file was generated by Sencha Designer version 2.0.0.
 * http://www.sencha.com/products/designer/
 *
 * This file requires use of the Ext JS 4.0.x library, under independent license.
 * License of Sencha Designer does not include license for Ext JS 4.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('TsmcBuddy.view.TopViewport', {
    extend: 'Ext.container.Viewport',

    layout: {
        type: 'fit'
    },

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'tabpanel',
                    id: 'mainTabPanel',
                    activeTab: 3,
                    items: [
                        {
                            xtype: 'panel',
                            html: '<iframe style="position:absolute;top:0px;left:0px;" width="100%" height="100%" src="http://f8cmydev1.tsmc.com.tw:7091/conf/main.do?operation=showComm" scrolling="no" frameborder="0"></iframe>',
                            id: 'pfPanel',
                            title: 'My',
                            tabConfig: {
                                xtype: 'tab',
                                tooltip: '目前連線至PeopleFinder的DEV環境，若是看不到內容，請按鈕進行NTLM認證。若仍然看不到，可能網址已變更，請等待更新版。'
                            },
                            items: [
                                {
                                    xtype: 'button',
                                    hidden: true,
                                    id: 'conf20Btn',
                                    margin: 20,
                                    style: 'position:absolute;z-index:1000000;',
                                    text: 'Click here for NTLM login first',
                                    listeners: {
                                        click: {
                                            fn: me.onConf20BtnClick,
                                            scope: me
                                        }
                                    }
                                }
                            ],
                            listeners: {
                                afterrender: {
                                    fn: me.onPfPanelAfterRender,
                                    scope: me
                                }
                            }
                        },
                        {
                            xtype: 'form',
                            id: 'callPanel',
                            layout: {
                                type: 'absolute'
                            },
                            title: 'Call',
                            tabConfig: {
                                xtype: 'tab',
                                tooltip: '撥打分機或MVPN手機 (目前已不支援外線電話)'
                            },
                            items: [
                                {
                                    xtype: 'textfield',
                                    id: 'callFromField',
                                    style: 'line-height:48px;',
                                    width: 260,
                                    fieldStyle: 'font-size:48px; height:60px;',
                                    fieldLabel: '',
                                    labelWidth: 50,
                                    allowBlank: false,
                                    emptyText: 'From',
                                    maxLength: 7,
                                    minLength: 7,
                                    regex: /7\d{6}/,
                                    regexText: 'Illegal phone number',
                                    x: 10,
                                    y: 10
                                },
                                {
                                    xtype: 'textfield',
                                    id: 'callToField',
                                    style: 'line-height:48px;',
                                    width: 260,
                                    fieldStyle: 'font-size:48px; height:60px;',
                                    fieldLabel: '',
                                    labelWidth: 50,
                                    allowBlank: false,
                                    emptyText: 'To',
                                    maxLength: 7,
                                    minLength: 7,
                                    regex: /7\d{6}/,
                                    regexText: 'Illegal phone number',
                                    x: 10,
                                    y: 80
                                },
                                {
                                    xtype: 'button',
                                    height: 30,
                                    id: 'callBtn',
                                    width: 260,
                                    text: 'GO',
                                    x: 10,
                                    y: 150
                                }
                            ]
                        },
                        {
                            xtype: 'panel',
                            id: 'smsPanel',
                            layout: {
                                type: 'absolute'
                            },
                            title: 'Text',
                            tabConfig: {
                                xtype: 'tab',
                                tooltip: '傳送SMS簡訊，目前可支援外部手機'
                            },
                            items: [
                                {
                                    xtype: 'textfield',
                                    id: 'smsBylineField',
                                    width: 260,
                                    fieldLabel: '',
                                    labelWidth: 50,
                                    emptyText: '署名',
                                    x: 10,
                                    y: 10
                                },
                                {
                                    xtype: 'textfield',
                                    id: 'smsDestField',
                                    width: 260,
                                    fieldLabel: '',
                                    labelWidth: 50,
                                    emptyText: '對方MVPN',
                                    x: 10,
                                    y: 40
                                },
                                {
                                    xtype: 'textareafield',
                                    height: 140,
                                    id: 'smsTextField',
                                    width: 260,
                                    fieldLabel: '',
                                    emptyText: '簡訊內容',
                                    x: 10,
                                    y: 70
                                },
                                {
                                    xtype: 'button',
                                    height: 30,
                                    width: 260,
                                    text: 'GO',
                                    x: 10,
                                    y: 220,
                                    listeners: {
                                        click: {
                                            fn: me.onSmsButtonClick,
                                            scope: me
                                        }
                                    }
                                }
                            ]
                        },
                        {
                            xtype: 'form',
                            id: 'pwPanel',
                            layout: {
                                type: 'absolute'
                            },
                            title: 'Pass',
                            tabConfig: {
                                xtype: 'tab',
                                tooltip: '重設NT或Notes密碼。<br/><br/>NT密碼：可直接覆蓋，無須考慮重複問題<br/><br/>Notes密碼：按GO之後會亂數修改密碼49次，最後一次才會改為畫面上的新密碼。'
                            },
                            items: [
                                {
                                    xtype: 'textfield',
                                    id: 'pwNtField',
                                    width: 250,
                                    name: 'RequestUser',
                                    allowBlank: false,
                                    emptyText: '帳號(NT)',
                                    vtype: 'alpha',
                                    x: 10,
                                    y: 40
                                },
                                {
                                    xtype: 'textfield',
                                    id: 'pwIdField',
                                    width: 250,
                                    name: 'UserID',
                                    allowBlank: false,
                                    emptyText: '身分證字號',
                                    vtype: 'alphanum',
                                    x: 10,
                                    y: 70
                                },
                                {
                                    xtype: 'datefield',
                                    id: 'pwDateField',
                                    width: 250,
                                    allowBlank: false,
                                    emptyText: '出生年月日',
                                    format: 'Y/m/d',
                                    showToday: false,
                                    x: 10,
                                    y: 100,
                                    listeners: {
                                        expand: {
                                            fn: me.onDatefieldExpand,
                                            scope: me
                                        }
                                    }
                                },
                                {
                                    xtype: 'textfield',
                                    id: 'pwTelField',
                                    width: 250,
                                    name: 'TEL',
                                    allowBlank: false,
                                    emptyText: '家中電話末六碼',
                                    enforceMaxLength: true,
                                    maxLength: 6,
                                    minLength: 6,
                                    x: 10,
                                    y: 130
                                },
                                {
                                    xtype: 'textfield',
                                    id: 'pwEmergencyField',
                                    width: 250,
                                    name: 'Emergency',
                                    emptyText: '緊急聯絡人',
                                    x: 10,
                                    y: 160
                                },
                                {
                                    xtype: 'textfield',
                                    id: 'pwField',
                                    width: 250,
                                    fieldStyle: 'background:url(images/captcha.jpg)',
                                    name: 'Password1',
                                    allowBlank: false,
                                    emptyText: '新密碼',
                                    x: 10,
                                    y: 190
                                },
                                {
                                    xtype: 'radiogroup',
                                    id: 'pwTypeRadio',
                                    width: 310,
                                    fieldLabel: '',
                                    allowBlank: false,
                                    x: 10,
                                    y: 10,
                                    items: [
                                        {
                                            xtype: 'radiofield',
                                            name: 'type',
                                            boxLabel: '重設Notes密碼(50循環)',
                                            inputValue: 'notes'
                                        },
                                        {
                                            xtype: 'radiofield',
                                            name: 'type',
                                            boxLabel: '重設NT密碼',
                                            checked: true,
                                            inputValue: 'nt'
                                        }
                                    ],
                                    listeners: {
                                        change: {
                                            fn: me.onPwTypeRadioChange,
                                            scope: me
                                        }
                                    }
                                },
                                {
                                    xtype: 'button',
                                    height: 30,
                                    width: 250,
                                    text: 'GO',
                                    x: 10,
                                    y: 220,
                                    listeners: {
                                        click: {
                                            fn: me.onPwButtonClick,
                                            scope: me
                                        }
                                    }
                                }
                            ]
                        },
                        {
                            xtype: 'form',
                            id: 'workPanel',
                            layout: {
                                type: 'absolute'
                            },
                            title: 808,
                            tabConfig: {
                                xtype: 'tab',
                                tooltip: '工時統計&上下班打卡'
                            },
                            items: [
                                {
                                    xtype: 'timefield',
                                    id: 'workTimeField',
                                    width: 300,
                                    value: new Date(),
                                    fieldLabel: '最後活動時間',
                                    labelWidth: 90,
                                    increment: 10,
                                    x: 10,
                                    y: 10
                                },
                                {
                                    xtype: 'button',
                                    height: 30,
                                    id: 'checkOutBtn',
                                    width: 300,
                                    text: '下班打卡',
                                    x: 10,
                                    y: 40,
                                    listeners: {
                                        click: {
                                            fn: me.onCheckOutBtnClick,
                                            scope: me
                                        }
                                    }
                                },
                                {
                                    xtype: 'button',
                                    height: 30,
                                    id: 'logBtn',
                                    width: 300,
                                    text: '查看打卡記錄',
                                    x: 10,
                                    y: 80,
                                    listeners: {
                                        click: {
                                            fn: me.onLogBtnClick,
                                            scope: me
                                        }
                                    }
                                },
                                {
                                    xtype: 'textareafield',
                                    height: 130,
                                    hidden: true,
                                    id: 'workHourText',
                                    width: 300,
                                    x: 10,
                                    y: 340
                                },
                                {
                                    xtype: 'chart',
                                    height: 230,
                                    id: 'workHourChart',
                                    width: 330,
                                    animate: true,
                                    store: 'WorkHourStore',
                                    x: -5,
                                    y: 110,
                                    series: [
                                        {
                                            type: 'line',
                                            xField: 'date',
                                            yField: [
                                                'time'
                                            ],
                                            smooth: 3
                                        }
                                    ],
                                    axes: [
                                        {
                                            type: 'Time',
                                            fields: [
                                                'time'
                                            ],
                                            position: 'left',
                                            dateFormat: 'gA',
                                            step: [
                                                'h',
                                                1
                                            ]
                                        }
                                    ]
                                }
                            ]
                        }
                    ],
                    listeners: {
                        tabchange: {
                            fn: me.onMainTabPanelTabChange,
                            scope: me
                        }
                    }
                }
            ]
        });

        me.callParent(arguments);
    },

    onConf20BtnClick: function(button, e, options) {
        window.open('http://f8cmydev1.tsmc.com.tw:7091/conf/main.do?operation=showComm&dispType=conference','_blank');

    },

    onPfPanelAfterRender: function(abstractcomponent, options) {
        var me = this;
        Ext.Ajax.request({
            method: 'GET',
            url: 'http://f8cmydev1.tsmc.com.tw:7091/conf/main.do?operation=showComm&dispType=conference',
            success: function(response){
            },
            failure: function(response){
                Ext.getCmp('conf20Btn').show();
            }
        });

    },

    onSmsButtonClick: function(button, e, options) {
        button.disable();
        Ext.Ajax.request({
            method: 'POST',
            url: 'http://f8cmydev1.tsmc.com.tw:7091/conf/phone.do',
            params:{
                operation: 'sendSms',
                sender: Ext.getCmp('smsBylineField').getValue(),
                sendSmsObjArry:Ext.encode([{
                    "id":"",
                    "ntAccount":"",
                    "phone": Ext.getCmp('smsDestField').getValue(),
                    "name":"test",
                "isMvpn":1}]),
                text: Ext.getCmp('smsTextField').getValue()
            },
            success: function(response){
                var result = Ext.decode(response.responseText);
                if(result.message.toUpperCase().search('FAIL')>=0){            
                    Ext.Msg.alert('傳送失敗',result.message);
                }else{
                    var info = Ext.Msg.show({
                        title:'傳送成功',
                        msg: result.message + '<br/>' + '本訊息將於1秒後自動關閉'
                    });
                    Ext.Function.defer(function(){
                        info.hide();
                    },2000);
                }
                button.enable();
            },
            failure: function(response){
                var result = Ext.decode(response.responseText);
                Ext.Msg.alert('傳送失敗',result.msg);
                button.enable();
            }
        });
    },

    onDatefieldExpand: function(field, options) {
        field.getPicker().setValue(new Date(1980,0,1));
        field.getPicker().showMonthPicker();
    },

    onPwTypeRadioChange: function(field, newValue, oldValue, options) {
        if(newValue.type == 'notes'){
            Ext.Msg.confirm('Confirm',
            '此功能需要花費較長時間，是否開啟新視窗以避免不小心按掉？',
            function(btn){
                if(btn=='yes'){
                    window.open('designer.html');
                }
            });
        }
    },

    onPwButtonClick: function(button, e, options) {

        if(Ext.getCmp('pwPanel').getForm().isValid()){


            var birthYear = Ext.getCmp('pwDateField').getValue().getFullYear();
            var birthMonth = Ext.getCmp('pwDateField').getValue().getMonth() +1;
            var birthDay = Ext.getCmp('pwDateField').getValue().getDate();


            if(Ext.getCmp('pwTypeRadio').getValue().type == 'nt'){
                Ext.Ajax.request({
                    url: 'http://pcmsweb/resetpassword/default.asp',
                    method: 'POST',
                    params: {
                        RequestUser: Ext.getCmp('pwNtField').getValue(),
                        UserID: Ext.getCmp('pwIdField').getValue(),
                        BirthYear: birthYear,
                        BirthMonth: birthMonth,
                        BirthDay: birthDay,
                        TEL: Ext.getCmp('pwTelField').getValue(),
                        Password1: Ext.getCmp('pwField').getValue(),
                        Password2: Ext.getCmp('pwField').getValue(),
                        Action:'submit'
                    },
                    success: function(response){

                    }
                });

            }else{

                notesSubmitting = true;
                notesSubmitCount = 0;
                notesSubmitHistory = '更改紀錄：';  
                notesSubmitProgress = Ext.Msg.show({
                    id: 'notesSubmitProgress',
                    title: 'Notes密碼更改中',
                    msg: '請耐心等候，勿關閉視窗',
                    progress: true,
                    closable: false,
                    buttons: Ext.Msg.CANCEL,
                    progressText: '0/' + notesCycle,
                    fn: function(btn){
                        if(btn == 'cancel'){
                            notesSubmitting = false;
                            Ext.Msg.alert('Cancelled','<textarea cols="50" rows="20">' + notesSubmitHistory+'</textarea>');
                        }
                    }
                });
                notesSubmit();
            }

        }
    },

    onCheckOutBtnClick: function(button, e, options) {

        var dateStr = Ext.util.Format.date(new Date(),'Y/m/d');
        var timeStr = Ext.util.Format.date(Ext.getCmp('workTimeField').getValue(),'H:i');

        if(timeStr.split(':')[0] < 8){
            var today = new Date();
            today.setDate(today.getDate()-1);
            var yesterday = Ext.util.Format.date(today,'Y/m/d');
            Ext.Msg.confirm('太晚下班了吧',
            '如果要算在'+yesterday+'請按Yes，<br/>要算在'+dateStr+'請按No。',
            function(btn){
                if(btn=='yes'){
                    dateStr = yesterday;
                }
                doCheckOut();
            });
        }else{
            doCheckOut();
        }

        function doCheckOut(){
            kango.invokeAsync('kango.storage.getItem', 'work_log', function(data) {
                if(Ext.isEmpty(data)){
                    data = [];
                }
                var duplicate = -1;
                Ext.Array.each(data,function(item){
                    if(item.date == dateStr){
                        duplicate = Ext.Array.indexOf(data,item);
                        return false;
                    }
                },undefined,true);
                if(duplicate >= 0){
                    Ext.Array.erase(data,duplicate,1);
                }
                data.push({
                    date: dateStr,
                    time: timeStr
                });

                kango.invokeAsync('kango.storage.setItem', 'work_log', data, function() {
                    Ext.Msg.alert('打卡成功','今天('+dateStr+')下班時間：'+timeStr);
                });

            });
        }
    },

    onLogBtnClick: function(button, e, options) {
        kango.invokeAsync('kango.storage.getItem', 'work_log', function(data) {
            var str = '';
            Ext.getStore('WorkHourStore').loadData(data);
            Ext.Array.each(data,function(item){
                str += item.date + ': ' +item.time+'\n';
            });

            Ext.getCmp('workHourText').setValue(str);
            Ext.getCmp('workHourText').show();
        });
    },

    onMainTabPanelTabChange: function(tabPanel, newCard, oldCard, options) {
        kango.invokeAsync('kango.ui.browserButton.setBadgeValue',newCard.title);
        Ext.getCmp('workTimeField').setValue(
        Ext.util.Format.date(new Date(),'g:i A')
        );
    }

});